//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSSM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Encargo
    {
        public int IDEncargo { get; set; }
        public string NombreCliente { get; set; }
        public string NumeroDeTelefono { get; set; }
        public Nullable<double> Valor { get; set; }
        public Nullable<double> Abono { get; set; }
        public Nullable<int> Encargado { get; set; }
        public string Observacion { get; set; }
        public Nullable<int> TipoTrabajo { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> FechaEntrada { get; set; }
        public Nullable<System.DateTime> FechaSalida { get; set; }
    }
}
