//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSSM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logs
    {
        public int LogID { get; set; }
        public string Elemento { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Usuario { get; set; }
        public string Descripcion { get; set; }
    }
}
