//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSSM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trabajo
    {
        public int IDTrabajo { get; set; }
        public Nullable<int> TipoTrabajo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Cliente { get; set; }
        public Nullable<double> Valor { get; set; }
        public string Link { get; set; }
        public Nullable<System.DateTime> FechaEntrada { get; set; }
        public Nullable<System.DateTime> FechaSalida { get; set; }
        public Nullable<int> Usuario { get; set; }
        public string Estado { get; set; }
    }
}
